Fix integration test

diff --git a/.github/workflows/integration_tests.yml b/.github/workflows/integration_tests.yml
--- a/.github/workflows/integration_tests.yml
+++ b/.github/workflows/integration_tests.yml
@@ -33,10 +33,16 @@ jobs:
 
       - name: Write config file
         run: |
-          echo '{ "github": { "issue": "ioki-mobility/summaraizer/11" } }' > config.json
+          echo '{ "github": { "token": "${{ secrets.GITHUB_TOKEN }}" } }' > config.json
 
       - name: Fetch github issue
-        run: go run cmd/summaraizer/summaraizer.go github
+        run: |
+          result=$(go run cmd/summaraizer/summaraizer.go github --issue ioki-mobility/summaraizer/1)
+          if [ "$result" = '[{"Author":"","Body":""}]' ]; then
+            echo "Error: Empty result"
+            exit 1
+          fi
+          echo "$result"
 
   summarizeOllama:
     runs-on: ubuntu-latest
